language: android

android:
  components:
    - platform-tools
    - build-tools-19.0.3
    - android-19
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - nvm install 4
    - npm install -g nativescript --ignore-scripts
    - npm install

before_script:
    - echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - tns usage-reporting disable
    #- tns error-reporting disable
    - tns platform add android
    - tns test android --emulator --justlaunch
